// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * Kind classifies a discovered target. New kinds may be added as more
 * providers come online — UI groups by Kind so unknown values render as
 * their string label.
 */
export enum Kind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    KindRun = "run",
    KindTest = "test",
    KindBenchmark = "benchmark",
    KindExample = "example",
    KindAttach = "attach",
};

/**
 * LaunchResult mirrors services.StartResult so the frontend can register the
 * session in its store immediately, without waiting for a session:event with
 * a cfgId that resolves to a workspace config (discovery targets aren't in
 * workspace.configs — they're a separate, virtual list).
 */
export class LaunchResult {
    "sessionId": string;
    "cfgId": string;
    "label": string;
    "state": string;
    "port": number;
    "pid": number;
    "cfg": config$0.LaunchConfig;
    "error"?: string;

    /** Creates a new LaunchResult instance. */
    constructor($$source: Partial<LaunchResult> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("cfgId" in $$source)) {
            this["cfgId"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("pid" in $$source)) {
            this["pid"] = 0;
        }
        if (!("cfg" in $$source)) {
            this["cfg"] = (new config$0.LaunchConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LaunchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): LaunchResult {
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("cfg" in $$parsedSource) {
            $$parsedSource["cfg"] = $$createField6_0($$parsedSource["cfg"]);
        }
        return new LaunchResult($$parsedSource as Partial<LaunchResult>);
    }
}

/**
 * Target is a single thing the user can launch or attach. IDs are stable
 * across refreshes for the same logical target so UI selection / running
 * state survives a re-scan.
 */
export class Target {
    "id": string;
    "provider": string;
    "kind": Kind;
    "label": string;
    "description"?: string;
    "dir": string;
    "program": string;
    "args"?: string[];
    "env"?: { [_ in string]?: string };

    /**
     * EnvFiles are the dotenv files discovered for this target, in order
     * of precedence (later entries override earlier). The launcher loads
     * each file and merges the values into the launch env at run time.
     */
    "envFiles"?: string[];

    /**
     * PID is set for KindAttach targets.
     */
    "pid"?: number;

    /**
     * Source location for "go to definition" affordance in the UI.
     */
    "sourceFile"?: string;
    "sourceLine"?: number;

    /** Creates a new Target instance. */
    constructor($$source: Partial<Target> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = Kind.$zero;
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("dir" in $$source)) {
            this["dir"] = "";
        }
        if (!("program" in $$source)) {
            this["program"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Target instance from a string or object.
     */
    static createFrom($$source: any = {}): Target {
        const $$createField7_0 = $$createType1;
        const $$createField8_0 = $$createType2;
        const $$createField9_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("args" in $$parsedSource) {
            $$parsedSource["args"] = $$createField7_0($$parsedSource["args"]);
        }
        if ("env" in $$parsedSource) {
            $$parsedSource["env"] = $$createField8_0($$parsedSource["env"]);
        }
        if ("envFiles" in $$parsedSource) {
            $$parsedSource["envFiles"] = $$createField9_0($$parsedSource["envFiles"]);
        }
        return new Target($$parsedSource as Partial<Target>);
    }
}

/**
 * TargetList is what the frontend renders. We return targets and a `stale`
 * flag so the UI can show "results from prior scan, refreshing…" if the
 * user opens the panel while a Refresh is in flight.
 */
export class TargetList {
    "root": string;
    "targets": Target[];
    "stale": boolean;
    "lastScanned": time$0.Time;

    /** Creates a new TargetList instance. */
    constructor($$source: Partial<TargetList> = {}) {
        if (!("root" in $$source)) {
            this["root"] = "";
        }
        if (!("targets" in $$source)) {
            this["targets"] = [];
        }
        if (!("stale" in $$source)) {
            this["stale"] = false;
        }
        if (!("lastScanned" in $$source)) {
            this["lastScanned"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TargetList instance from a string or object.
     */
    static createFrom($$source: any = {}): TargetList {
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("targets" in $$parsedSource) {
            $$parsedSource["targets"] = $$createField1_0($$parsedSource["targets"]);
        }
        return new TargetList($$parsedSource as Partial<TargetList>);
    }
}

// Private type creation functions
const $$createType0 = config$0.LaunchConfig.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = Target.createFrom;
const $$createType4 = $Create.Array($$createType3);
