// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails-bound entry point for the run/attach panel. It owns
 * the registry, holds a per-workspace cache, and brokers Launch calls back
 * into the session manager so the frontend can use one binding for both
 * "discover targets" and "run target".
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Launch starts a session for the given target ID. Env files attached to
 * the target are merged into the LaunchConfig.Env in walk-up order (the
 * outermost file's vars are written first, then each subsequent file
 * overrides) — matching dotenv-cli precedence.
 */
export function Launch(targetID: string): $CancellablePromise<$models.LaunchResult> {
    return $Call.ByID(3448038124, targetID).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * LaunchProcess starts an attach session for an arbitrary PID supplied by
 * the user (manual picker fallback). The caller provides the workspace
 * root via ws.Root(); we synthesize a Target on the fly.
 */
export function LaunchProcess(pid: number): $CancellablePromise<$models.LaunchResult> {
    return $Call.ByID(676986689, pid).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Refresh re-runs every provider against the active workspace root and
 * streams results via Wails events. The frontend can either rely on the
 * streamed events or re-poll Targets() once `discovery:done` fires.
 * 
 * Events emitted (all carry workspace root as `root`):
 *   - discovery:start    {root}
 *   - discovery:targets  {root, targets}    (full replacement on completion)
 *   - discovery:done     {root, count}
 */
export function Refresh(): $CancellablePromise<$models.Target[]> {
    return $Call.ByID(1059789446).then(($result: any) => {
        return $$createType2($result);
    });
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(1477919008, app);
}

/**
 * Targets returns whatever's in the cache for the active workspace, without
 * kicking off a scan. Use Refresh for that. Empty cache → empty list (the
 * UI calls Refresh on first open).
 */
export function Targets(): $CancellablePromise<$models.TargetList> {
    return $Call.ByID(3857416623).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = $models.LaunchResult.createFrom;
const $$createType1 = $models.Target.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.TargetList.createFrom;
