// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";

export class DetectedSource {
    /**
     * Creates a new DetectedSource instance.
     * @param {Partial<DetectedSource>} [$$source = {}] - The source object to create the DetectedSource.
     */
    constructor($$source = {}) {
        if (!("editor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["editor"] = "";
        }
        if (!("projectPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["projectPath"] = "";
        }
        if (!("configPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["configPath"] = "";
        }
        if (!("configCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["configCount"] = 0;
        }
        if (!("configs" in $$source)) {
            /**
             * @member
             * @type {config$0.LaunchConfig[]}
             */
            this["configs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DetectedSource instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DetectedSource}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("configs" in $$parsedSource) {
            $$parsedSource["configs"] = $$createField4_0($$parsedSource["configs"]);
        }
        return new DetectedSource(/** @type {Partial<DetectedSource>} */($$parsedSource));
    }
}

export class FolderScanResult {
    /**
     * Creates a new FolderScanResult instance.
     * @param {Partial<FolderScanResult>} [$$source = {}] - The source object to create the FolderScanResult.
     */
    constructor($$source = {}) {
        if (!("editorConfigs" in $$source)) {
            /**
             * @member
             * @type {DetectedSource[]}
             */
            this["editorConfigs"] = [];
        }
        if (!("runTargets" in $$source)) {
            /**
             * @member
             * @type {RunTarget[]}
             */
            this["runTargets"] = [];
        }
        if (!("projectPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["projectPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FolderScanResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FolderScanResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("editorConfigs" in $$parsedSource) {
            $$parsedSource["editorConfigs"] = $$createField0_0($$parsedSource["editorConfigs"]);
        }
        if ("runTargets" in $$parsedSource) {
            $$parsedSource["runTargets"] = $$createField1_0($$parsedSource["runTargets"]);
        }
        return new FolderScanResult(/** @type {Partial<FolderScanResult>} */($$parsedSource));
    }
}

export class RunTarget {
    /**
     * Creates a new RunTarget instance.
     * @param {Partial<RunTarget>} [$$source = {}] - The source object to create the RunTarget.
     */
    constructor($$source = {}) {
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * "run" or "test"
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("package" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["package"] = "";
        }
        if (!("dir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunTarget instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RunTarget}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RunTarget(/** @type {Partial<RunTarget>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = config$0.LaunchConfig.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = DetectedSource.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = RunTarget.createFrom;
const $$createType5 = $Create.Array($$createType4);
