// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";

export class DetectedSource {
    "editor": string;
    "projectPath": string;
    "configPath": string;
    "configCount": number;
    "configs": config$0.LaunchConfig[];

    /** Creates a new DetectedSource instance. */
    constructor($$source: Partial<DetectedSource> = {}) {
        if (!("editor" in $$source)) {
            this["editor"] = "";
        }
        if (!("projectPath" in $$source)) {
            this["projectPath"] = "";
        }
        if (!("configPath" in $$source)) {
            this["configPath"] = "";
        }
        if (!("configCount" in $$source)) {
            this["configCount"] = 0;
        }
        if (!("configs" in $$source)) {
            this["configs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DetectedSource instance from a string or object.
     */
    static createFrom($$source: any = {}): DetectedSource {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("configs" in $$parsedSource) {
            $$parsedSource["configs"] = $$createField4_0($$parsedSource["configs"]);
        }
        return new DetectedSource($$parsedSource as Partial<DetectedSource>);
    }
}

export class FolderScanResult {
    "editorConfigs": DetectedSource[];
    "runTargets": RunTarget[];
    "projectPath": string;

    /** Creates a new FolderScanResult instance. */
    constructor($$source: Partial<FolderScanResult> = {}) {
        if (!("editorConfigs" in $$source)) {
            this["editorConfigs"] = [];
        }
        if (!("runTargets" in $$source)) {
            this["runTargets"] = [];
        }
        if (!("projectPath" in $$source)) {
            this["projectPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FolderScanResult instance from a string or object.
     */
    static createFrom($$source: any = {}): FolderScanResult {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("editorConfigs" in $$parsedSource) {
            $$parsedSource["editorConfigs"] = $$createField0_0($$parsedSource["editorConfigs"]);
        }
        if ("runTargets" in $$parsedSource) {
            $$parsedSource["runTargets"] = $$createField1_0($$parsedSource["runTargets"]);
        }
        return new FolderScanResult($$parsedSource as Partial<FolderScanResult>);
    }
}

export class RunTarget {
    "label": string;

    /**
     * "run" or "test"
     */
    "kind": string;
    "package": string;
    "dir": string;

    /** Creates a new RunTarget instance. */
    constructor($$source: Partial<RunTarget> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("package" in $$source)) {
            this["package"] = "";
        }
        if (!("dir" in $$source)) {
            this["dir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunTarget instance from a string or object.
     */
    static createFrom($$source: any = {}): RunTarget {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RunTarget($$parsedSource as Partial<RunTarget>);
    }
}

// Private type creation functions
const $$createType0 = config$0.LaunchConfig.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = DetectedSource.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = RunTarget.createFrom;
const $$createType5 = $Create.Array($$createType4);
