// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";

export class DetectedSource {
    /**
     * Creates a new DetectedSource instance.
     * @param {Partial<DetectedSource>} [$$source = {}] - The source object to create the DetectedSource.
     */
    constructor($$source = {}) {
        if (!("editor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["editor"] = "";
        }
        if (!("projectPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["projectPath"] = "";
        }
        if (!("configPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["configPath"] = "";
        }
        if (!("configCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["configCount"] = 0;
        }
        if (!("configs" in $$source)) {
            /**
             * @member
             * @type {config$0.LaunchConfig[]}
             */
            this["configs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DetectedSource instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DetectedSource}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("configs" in $$parsedSource) {
            $$parsedSource["configs"] = $$createField4_0($$parsedSource["configs"]);
        }
        return new DetectedSource(/** @type {Partial<DetectedSource>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = config$0.LaunchConfig.createFrom;
const $$createType1 = $Create.Array($$createType0);
