// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is exposed to the frontend via Wails bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateConfigFromTargets writes a synthetic debug.json from run targets and imports it.
 */
export function CreateConfigFromTargets(projectDir: string, targets: $models.RunTarget[]): $CancellablePromise<void> {
    return $Call.ByID(593295708, projectDir, targets);
}

/**
 * Import imports a detected source's config file into the debug files store.
 */
export function Import(configPath: string): $CancellablePromise<void> {
    return $Call.ByID(899976173, configPath);
}

/**
 * ImportAll imports all detected sources from a project.
 */
export function ImportAll(sources: $models.DetectedSource[]): $CancellablePromise<void> {
    return $Call.ByID(1562390140, sources);
}

/**
 * ImportConfigs creates a synthetic debug.json from detected configs and imports it.
 * Used for GoLand configs which are spread across multiple XML files.
 */
export function ImportConfigs(projectPath: string, editor: string, configs: config$0.LaunchConfig[]): $CancellablePromise<void> {
    return $Call.ByID(4166207140, projectPath, editor, configs);
}

/**
 * IsImported checks if a config path is already in the debug files store.
 */
export function IsImported(configPath: string): $CancellablePromise<boolean> {
    return $Call.ByID(1347731116, configPath);
}

/**
 * PickAndScanFolder opens a native folder picker and scans the chosen
 * directory for editor configs (Zed/VSCode/GoLand). Used by the import UI
 * to let users add folders by hand alongside the system-wide scan.
 * 
 * Returns ProjectPath="" with no editor configs if the user cancelled. A
 * folder with zero configs returns ProjectPath set but EditorConfigs nil —
 * the UI surfaces this as "no configs found, open as workspace anyway?".
 */
export function PickAndScanFolder(): $CancellablePromise<$models.FolderScanResult> {
    return $Call.ByID(95908803).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Scan discovers debug configs from known editor locations across the system.
 */
export function Scan(): $CancellablePromise<$models.DetectedSource[]> {
    return $Call.ByID(1470118857).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ScanDir scans a specific directory (user-chosen via folder picker).
 */
export function ScanDir(dir: string): $CancellablePromise<$models.DetectedSource[]> {
    return $Call.ByID(862359768, dir).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ScanFolder scans a specific folder for editor configs and Go run/test targets.
 */
export function ScanFolder(dir: string): $CancellablePromise<$models.FolderScanResult> {
    return $Call.ByID(2996424521, dir).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(3479422059, app);
}

// Private type creation functions
const $$createType0 = $models.FolderScanResult.createFrom;
const $$createType1 = $models.DetectedSource.createFrom;
const $$createType2 = $Create.Array($$createType1);
