// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is exposed to the frontend via Wails bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateConfigFromTargets writes a synthetic debug.json from run targets and imports it.
 * @param {string} projectDir
 * @param {$models.RunTarget[]} targets
 * @returns {$CancellablePromise<void>}
 */
export function CreateConfigFromTargets(projectDir, targets) {
    return $Call.ByID(593295708, projectDir, targets);
}

/**
 * Import imports a detected source's config file into the debug files store.
 * @param {string} configPath
 * @returns {$CancellablePromise<void>}
 */
export function Import(configPath) {
    return $Call.ByID(899976173, configPath);
}

/**
 * ImportAll imports all detected sources from a project.
 * @param {$models.DetectedSource[]} sources
 * @returns {$CancellablePromise<void>}
 */
export function ImportAll(sources) {
    return $Call.ByID(1562390140, sources);
}

/**
 * ImportConfigs creates a synthetic debug.json from detected configs and imports it.
 * Used for GoLand configs which are spread across multiple XML files.
 * @param {string} projectPath
 * @param {string} editor
 * @param {config$0.LaunchConfig[]} configs
 * @returns {$CancellablePromise<void>}
 */
export function ImportConfigs(projectPath, editor, configs) {
    return $Call.ByID(4166207140, projectPath, editor, configs);
}

/**
 * IsImported checks if a config path is already in the debug files store.
 * @param {string} configPath
 * @returns {$CancellablePromise<boolean>}
 */
export function IsImported(configPath) {
    return $Call.ByID(1347731116, configPath);
}

/**
 * Scan discovers debug configs from known editor locations across the system.
 * @returns {$CancellablePromise<$models.DetectedSource[]>}
 */
export function Scan() {
    return $Call.ByID(1470118857).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ScanDir scans a specific directory (user-chosen via folder picker).
 * @param {string} dir
 * @returns {$CancellablePromise<$models.DetectedSource[]>}
 */
export function ScanDir(dir) {
    return $Call.ByID(862359768, dir).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ScanFolder scans a specific folder for editor configs and Go run/test targets.
 * @param {string} dir
 * @returns {$CancellablePromise<$models.FolderScanResult>}
 */
export function ScanFolder(dir) {
    return $Call.ByID(2996424521, dir).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(3479422059, app);
}

// Private type creation functions
const $$createType0 = $models.DetectedSource.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.FolderScanResult.createFrom;
