// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * Entry represents one project. The unit is always a folder; if the project's
 * launch configs live somewhere outside the standard `.zed`/`.vscode`/
 * `.delveui` locations (e.g. an externally-shared launch.json), `LaunchFile`
 * records that explicit override.
 * 
 * `Stale` is computed at load — it is true when `Path` no longer exists on
 * disk. The frontend renders stale entries dimmed with a remove affordance.
 */
export class Entry {
    "id": string;
    "path": string;
    "label": string;
    "launchFile"?: string;
    "addedAt": time$0.Time;
    "lastUsed"?: time$0.Time;
    "configs": config$0.LaunchConfig[];

    /** Creates a new Entry instance. */
    constructor($$source: Partial<Entry> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("addedAt" in $$source)) {
            this["addedAt"] = null;
        }
        if (!("configs" in $$source)) {
            this["configs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Entry instance from a string or object.
     */
    static createFrom($$source: any = {}): Entry {
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("configs" in $$parsedSource) {
            $$parsedSource["configs"] = $$createField6_0($$parsedSource["configs"]);
        }
        return new Entry($$parsedSource as Partial<Entry>);
    }
}

// Private type creation functions
const $$createType0 = config$0.LaunchConfig.createFrom;
const $$createType1 = $Create.Array($$createType0);
