// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Add(path: string): $CancellablePromise<$models.Entry> {
    return $Call.ByID(749921156, path).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetDefault(): $CancellablePromise<$models.Entry | null> {
    return $Call.ByID(1386815440).then(($result: any) => {
        return $$createType1($result);
    });
}

export function List(): $CancellablePromise<$models.Entry[]> {
    return $Call.ByID(496274225).then(($result: any) => {
        return $$createType2($result);
    });
}

export function Reload(id: string): $CancellablePromise<void> {
    return $Call.ByID(3438039068, id);
}

export function ReloadAll(): $CancellablePromise<void> {
    return $Call.ByID(1108768007);
}

export function Remove(id: string): $CancellablePromise<void> {
    return $Call.ByID(250174573, id);
}

export function SetDefault(id: string): $CancellablePromise<void> {
    return $Call.ByID(4003068100, id);
}

// Private type creation functions
const $$createType0 = $models.Entry.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
