// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileService reads source files for the editor view.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function ReadFile(path: string): $CancellablePromise<string> {
    return $Call.ByID(1818965665, path);
}

export function WriteFile(path: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(502508328, path, content);
}
