// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileService reads source files for the editor view.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} dirPath
 * @returns {$CancellablePromise<$models.DirEntry[]>}
 */
export function ListDir(dirPath) {
    return $Call.ByID(1748364066, dirPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} root
 * @returns {$CancellablePromise<string[]>}
 */
export function ListGoFiles(root) {
    return $Call.ByID(721462788, root).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function ReadFile(path) {
    return $Call.ByID(1818965665, path);
}

/**
 * @param {string} path
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function WriteFile(path, content) {
    return $Call.ByID(502508328, path, content);
}

// Private type creation functions
const $$createType0 = $models.DirEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
