// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileService reads source files for the editor view.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ListDir(dirPath: string): $CancellablePromise<$models.DirEntry[]> {
    return $Call.ByID(1748364066, dirPath).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListGoFiles(root: string): $CancellablePromise<string[]> {
    return $Call.ByID(721462788, root).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ReadFile(path: string): $CancellablePromise<string> {
    return $Call.ByID(1818965665, path);
}

export function WriteFile(path: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(502508328, path, content);
}

// Private type creation functions
const $$createType0 = $models.DirEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
