// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as session$0 from "../session/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as workspace$0 from "../workspace/models.js";

/**
 * ResourceInfo holds process resource stats.
 */
export class ResourceInfo {
    /**
     * Creates a new ResourceInfo instance.
     * @param {Partial<ResourceInfo>} [$$source = {}] - The source object to create the ResourceInfo.
     */
    constructor($$source = {}) {
        if (!("pid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pid"] = 0;
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["state"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("rssMb" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rssMb"] = 0;
        }
        if (!("cpu" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cpu"] = "";
        }
        if (!("elapsed" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["elapsed"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResourceInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ResourceInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResourceInfo(/** @type {Partial<ResourceInfo>} */($$parsedSource));
    }
}

export class SessionInfo {
    /**
     * Creates a new SessionInfo instance.
     * @param {Partial<SessionInfo>} [$$source = {}] - The source object to create the SessionInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("cfgId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cfgId"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {session$0.State}
             */
            this["state"] = session$0.State.$zero;
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("pid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pid"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SessionInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionInfo(/** @type {Partial<SessionInfo>} */($$parsedSource));
    }
}

/**
 * StartResult always carries session info when a session was created, even on
 * launch error. If Error is non-empty, the launch failed; the session may still
 * have captured stderr/stdout events worth displaying.
 */
export class StartResult {
    /**
     * Creates a new StartResult instance.
     * @param {Partial<StartResult>} [$$source = {}] - The source object to create the StartResult.
     */
    constructor($$source = {}) {
        if (!("session" in $$source)) {
            /**
             * @member
             * @type {SessionInfo}
             */
            this["session"] = (new SessionInfo());
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StartResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField0_0($$parsedSource["session"]);
        }
        return new StartResult(/** @type {Partial<StartResult>} */($$parsedSource));
    }
}

export class WorkspaceInfo {
    /**
     * Creates a new WorkspaceInfo instance.
     * @param {Partial<WorkspaceInfo>} [$$source = {}] - The source object to create the WorkspaceInfo.
     */
    constructor($$source = {}) {
        if (!("root" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["root"] = "";
        }
        if (!("debugFile" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["debugFile"] = "";
        }
        if (!("configs" in $$source)) {
            /**
             * @member
             * @type {config$0.LaunchConfig[]}
             */
            this["configs"] = [];
        }
        if (!("recents" in $$source)) {
            /**
             * @member
             * @type {workspace$0.Recent[]}
             */
            this["recents"] = [];
        }
        if (!("loadedOk" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["loadedOk"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["loadError"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WorkspaceInfo}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("configs" in $$parsedSource) {
            $$parsedSource["configs"] = $$createField2_0($$parsedSource["configs"]);
        }
        if ("recents" in $$parsedSource) {
            $$parsedSource["recents"] = $$createField3_0($$parsedSource["recents"]);
        }
        return new WorkspaceInfo(/** @type {Partial<WorkspaceInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = SessionInfo.createFrom;
const $$createType1 = config$0.LaunchConfig.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = workspace$0.Recent.createFrom;
const $$createType4 = $Create.Array($$createType3);
