// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as session$0 from "../session/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as workspace$0 from "../workspace/models.js";

/**
 * CleanResult is returned by CleanDebugBinaries.
 */
export class CleanResult {
    "dir": string;
    "removed": string[];
    "count": number;

    /** Creates a new CleanResult instance. */
    constructor($$source: Partial<CleanResult> = {}) {
        if (!("dir" in $$source)) {
            this["dir"] = "";
        }
        if (!("removed" in $$source)) {
            this["removed"] = [];
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CleanResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CleanResult {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("removed" in $$parsedSource) {
            $$parsedSource["removed"] = $$createField1_0($$parsedSource["removed"]);
        }
        return new CleanResult($$parsedSource as Partial<CleanResult>);
    }
}

export class DirEntry {
    "name": string;
    "path": string;
    "isDir": boolean;

    /** Creates a new DirEntry instance. */
    constructor($$source: Partial<DirEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("isDir" in $$source)) {
            this["isDir"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DirEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): DirEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DirEntry($$parsedSource as Partial<DirEntry>);
    }
}

/**
 * ResourceInfo holds process resource stats.
 */
export class ResourceInfo {
    "pid": number;
    "label": string;
    "state": string;
    "port": number;
    "rssMb": number;
    "cpu": string;
    "elapsed": string;

    /** Creates a new ResourceInfo instance. */
    constructor($$source: Partial<ResourceInfo> = {}) {
        if (!("pid" in $$source)) {
            this["pid"] = 0;
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("rssMb" in $$source)) {
            this["rssMb"] = 0;
        }
        if (!("cpu" in $$source)) {
            this["cpu"] = "";
        }
        if (!("elapsed" in $$source)) {
            this["elapsed"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResourceInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ResourceInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResourceInfo($$parsedSource as Partial<ResourceInfo>);
    }
}

export class SessionInfo {
    "id": string;
    "cfgId": string;
    "label": string;
    "state": session$0.State;
    "port": number;
    "pid": number;
    "cfg": config$0.LaunchConfig;

    /** Creates a new SessionInfo instance. */
    constructor($$source: Partial<SessionInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("cfgId" in $$source)) {
            this["cfgId"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = session$0.State.$zero;
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("pid" in $$source)) {
            this["pid"] = 0;
        }
        if (!("cfg" in $$source)) {
            this["cfg"] = (new config$0.LaunchConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionInfo {
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("cfg" in $$parsedSource) {
            $$parsedSource["cfg"] = $$createField6_0($$parsedSource["cfg"]);
        }
        return new SessionInfo($$parsedSource as Partial<SessionInfo>);
    }
}

/**
 * StartResult always carries session info when a session was created, even on
 * launch error. If Error is non-empty, the launch failed; the session may still
 * have captured stderr/stdout events worth displaying.
 */
export class StartResult {
    "session": SessionInfo;
    "error"?: string;

    /** Creates a new StartResult instance. */
    constructor($$source: Partial<StartResult> = {}) {
        if (!("session" in $$source)) {
            this["session"] = (new SessionInfo());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartResult instance from a string or object.
     */
    static createFrom($$source: any = {}): StartResult {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField0_0($$parsedSource["session"]);
        }
        return new StartResult($$parsedSource as Partial<StartResult>);
    }
}

export class WorkspaceInfo {
    "root": string;
    "debugFile": string;
    "configs": config$0.LaunchConfig[];
    "recents": workspace$0.Recent[];
    "loadedOk": boolean;
    "loadError"?: string;

    /** Creates a new WorkspaceInfo instance. */
    constructor($$source: Partial<WorkspaceInfo> = {}) {
        if (!("root" in $$source)) {
            this["root"] = "";
        }
        if (!("debugFile" in $$source)) {
            this["debugFile"] = "";
        }
        if (!("configs" in $$source)) {
            this["configs"] = [];
        }
        if (!("recents" in $$source)) {
            this["recents"] = [];
        }
        if (!("loadedOk" in $$source)) {
            this["loadedOk"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceInfo {
        const $$createField2_0 = $$createType3;
        const $$createField3_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("configs" in $$parsedSource) {
            $$parsedSource["configs"] = $$createField2_0($$parsedSource["configs"]);
        }
        if ("recents" in $$parsedSource) {
            $$parsedSource["recents"] = $$createField3_0($$parsedSource["recents"]);
        }
        return new WorkspaceInfo($$parsedSource as Partial<WorkspaceInfo>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = config$0.LaunchConfig.createFrom;
const $$createType2 = SessionInfo.createFrom;
const $$createType3 = $Create.Array($$createType1);
const $$createType4 = workspace$0.Recent.createFrom;
const $$createType5 = $Create.Array($$createType4);
