// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SessionService is exposed to the frontend: start/stop/control debug sessions.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AllResources(): $CancellablePromise<$models.ResourceInfo[]> {
    return $Call.ByID(153110581).then(($result: any) => {
        return $$createType1($result);
    });
}

export function AppResources(): $CancellablePromise<$models.ResourceInfo> {
    return $Call.ByID(4042149373).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CleanDebugBinaries removes Delve's auto-generated __debug_bin* files from
 * the current workspace root (recursively). Also sweeps each launch config's
 * cwd/program dir, since those may sit outside the workspace root.
 */
export function CleanDebugBinaries(): $CancellablePromise<$models.CleanResult> {
    return $Call.ByID(1589582440).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ConfigurationDone signals the DAP server that the client is finished with
 * configuration (e.g. setting breakpoints) so the program can resume.
 * Called by the frontend after start(), once breakpoints have been pushed.
 */
export function ConfigurationDone(id: string): $CancellablePromise<void> {
    return $Call.ByID(1168870977, id);
}

export function Continue(id: string): $CancellablePromise<void> {
    return $Call.ByID(304844008, id);
}

export function Evaluate(id: string, expr: string, frameID: number): $CancellablePromise<any> {
    return $Call.ByID(1558837486, id, expr, frameID);
}

/**
 * KillPort finds and kills the process listening on the given TCP port.
 */
export function KillPort(port: number): $CancellablePromise<void> {
    return $Call.ByID(10571950, port);
}

export function List(): $CancellablePromise<$models.SessionInfo[]> {
    return $Call.ByID(2563233365).then(($result: any) => {
        return $$createType4($result);
    });
}

export function Pause(id: string): $CancellablePromise<void> {
    return $Call.ByID(400221289, id);
}

export function Resources(id: string): $CancellablePromise<$models.ResourceInfo> {
    return $Call.ByID(4150888478, id).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Restart(id: string): $CancellablePromise<$models.StartResult> {
    return $Call.ByID(135540608, id).then(($result: any) => {
        return $$createType5($result);
    });
}

export function Scopes(id: string, frameID: number): $CancellablePromise<any> {
    return $Call.ByID(1631757612, id, frameID);
}

export function SetBreakpoints(id: string, sourcePath: string, lines: number[]): $CancellablePromise<any> {
    return $Call.ByID(690778005, id, sourcePath, lines);
}

export function SetExceptionBreakpoints(id: string, filters: string[]): $CancellablePromise<void> {
    return $Call.ByID(694059588, id, filters);
}

export function StackTrace(id: string, threadID: number): $CancellablePromise<any> {
    return $Call.ByID(1796857896, id, threadID);
}

export function Start(cfgID: string): $CancellablePromise<$models.StartResult> {
    return $Call.ByID(3762002571, cfgID).then(($result: any) => {
        return $$createType5($result);
    });
}

export function StepIn(id: string): $CancellablePromise<void> {
    return $Call.ByID(2888641856, id);
}

export function StepOut(id: string): $CancellablePromise<void> {
    return $Call.ByID(507509253, id);
}

export function StepOver(id: string): $CancellablePromise<void> {
    return $Call.ByID(2358189361, id);
}

export function Stop(id: string): $CancellablePromise<void> {
    return $Call.ByID(1991559545, id);
}

export function StopByCfg(cfgID: string): $CancellablePromise<void> {
    return $Call.ByID(2653623286, cfgID);
}

export function Threads(id: string): $CancellablePromise<any> {
    return $Call.ByID(198090730, id);
}

export function Variables(id: string, ref: number): $CancellablePromise<any> {
    return $Call.ByID(4165676102, id, ref);
}

// Private type creation functions
const $$createType0 = $models.ResourceInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.CleanResult.createFrom;
const $$createType3 = $models.SessionInfo.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.StartResult.createFrom;
