// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SessionService is exposed to the frontend: start/stop/control debug sessions.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.ResourceInfo[]>}
 */
export function AllResources() {
    return $Call.ByID(153110581).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.ResourceInfo>}
 */
export function AppResources() {
    return $Call.ByID(4042149373).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function Continue(id) {
    return $Call.ByID(304844008, id);
}

/**
 * @param {string} id
 * @param {string} expr
 * @param {number} frameID
 * @returns {$CancellablePromise<any>}
 */
export function Evaluate(id, expr, frameID) {
    return $Call.ByID(1558837486, id, expr, frameID);
}

/**
 * KillPort finds and kills the process listening on the given TCP port.
 * @param {number} port
 * @returns {$CancellablePromise<void>}
 */
export function KillPort(port) {
    return $Call.ByID(10571950, port);
}

/**
 * @returns {$CancellablePromise<$models.SessionInfo[]>}
 */
export function List() {
    return $Call.ByID(2563233365).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function Pause(id) {
    return $Call.ByID(400221289, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.ResourceInfo>}
 */
export function Resources(id) {
    return $Call.ByID(4150888478, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.StartResult>}
 */
export function Restart(id) {
    return $Call.ByID(135540608, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} id
 * @param {number} frameID
 * @returns {$CancellablePromise<any>}
 */
export function Scopes(id, frameID) {
    return $Call.ByID(1631757612, id, frameID);
}

/**
 * @param {string} id
 * @param {string} sourcePath
 * @param {number[]} lines
 * @returns {$CancellablePromise<any>}
 */
export function SetBreakpoints(id, sourcePath, lines) {
    return $Call.ByID(690778005, id, sourcePath, lines);
}

/**
 * @param {string} id
 * @param {string[]} filters
 * @returns {$CancellablePromise<void>}
 */
export function SetExceptionBreakpoints(id, filters) {
    return $Call.ByID(694059588, id, filters);
}

/**
 * @param {string} id
 * @param {number} threadID
 * @returns {$CancellablePromise<any>}
 */
export function StackTrace(id, threadID) {
    return $Call.ByID(1796857896, id, threadID);
}

/**
 * @param {string} cfgID
 * @returns {$CancellablePromise<$models.StartResult>}
 */
export function Start(cfgID) {
    return $Call.ByID(3762002571, cfgID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function StepIn(id) {
    return $Call.ByID(2888641856, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function StepOut(id) {
    return $Call.ByID(507509253, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function StepOver(id) {
    return $Call.ByID(2358189361, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function Stop(id) {
    return $Call.ByID(1991559545, id);
}

/**
 * @param {string} cfgID
 * @returns {$CancellablePromise<void>}
 */
export function StopByCfg(cfgID) {
    return $Call.ByID(2653623286, cfgID);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<any>}
 */
export function Threads(id) {
    return $Call.ByID(198090730, id);
}

/**
 * @param {string} id
 * @param {number} ref
 * @returns {$CancellablePromise<any>}
 */
export function Variables(id, ref) {
    return $Call.ByID(4165676102, id, ref);
}

// Private type creation functions
const $$createType0 = $models.ResourceInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.SessionInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.StartResult.createFrom;
