// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WorkspaceService is exposed to the frontend: open workspace, list configs, recents.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<config$0.LaunchConfig[]>}
 */
export function Configs() {
    return $Call.ByID(2808701759).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function DebugFile() {
    return $Call.ByID(3944010881);
}

/**
 * @returns {$CancellablePromise<$models.WorkspaceInfo>}
 */
export function Info() {
    return $Call.ByID(4193137668).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * OpenDebugFile loads an arbitrary debug.json path directly.
 * @param {string} path
 * @returns {$CancellablePromise<$models.WorkspaceInfo>}
 */
export function OpenDebugFile(path) {
    return $Call.ByID(4075017945, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * OpenWorkspace accepts either a directory (auto-discovers .zed/debug.json)
 * or a path to a debug.json file directly.
 * @param {string} path
 * @returns {$CancellablePromise<$models.WorkspaceInfo>}
 */
export function OpenWorkspace(path) {
    return $Call.ByID(2847427741, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * PickDebugFile opens a native file dialog for the user to choose a debug.json.
 * @returns {$CancellablePromise<$models.WorkspaceInfo>}
 */
export function PickDebugFile() {
    return $Call.ByID(1074223530).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * PickWorkspaceFolder opens a native dialog for a directory (auto-detect .zed/debug.json).
 * @returns {$CancellablePromise<$models.WorkspaceInfo>}
 */
export function PickWorkspaceFolder() {
    return $Call.ByID(3880060474).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function Root() {
    return $Call.ByID(1469185968);
}

/**
 * SetApp injects the running application so the service can open native dialogs.
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(1957069011, app);
}

// Private type creation functions
const $$createType0 = config$0.LaunchConfig.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.WorkspaceInfo.createFrom;
