// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AdapterInfo is the DTO sent to the frontend for each registered adapter.
 */
export class AdapterInfo {
    "language": string;
    "label": string;
    "description": string;
    "installed": boolean;
    "installCmd": string;
    "installUrl"?: string;
    "installing": boolean;
    "error"?: string;

    /** Creates a new AdapterInfo instance. */
    constructor($$source: Partial<AdapterInfo> = {}) {
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("installed" in $$source)) {
            this["installed"] = false;
        }
        if (!("installCmd" in $$source)) {
            this["installCmd"] = "";
        }
        if (!("installing" in $$source)) {
            this["installing"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AdapterInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): AdapterInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AdapterInfo($$parsedSource as Partial<AdapterInfo>);
    }
}
