// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails-bound entry point for the adapter settings panel.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Install starts an async installation for the given language. Emits events
 * adapter:install:output for each line and adapter:install:done on completion.
 */
export function Install(language: string): $CancellablePromise<void> {
    return $Call.ByID(2674087595, language);
}

/**
 * List returns all registered adapters with their current status.
 */
export function List(): $CancellablePromise<$models.AdapterInfo[]> {
    return $Call.ByID(2788802368).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SetApp injects the running application for event emission.
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(359066547, app);
}

// Private type creation functions
const $$createType0 = $models.AdapterInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
