// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class TerminalColors {
    "black": string;
    "red": string;
    "green": string;
    "yellow": string;
    "blue": string;
    "magenta": string;
    "cyan": string;
    "white": string;
    "brightBlack": string;
    "brightRed": string;
    "brightGreen": string;
    "brightYellow": string;
    "brightBlue": string;
    "brightMagenta": string;
    "brightCyan": string;
    "brightWhite": string;
    "background": string;
    "foreground": string;
    "cursor": string;

    /** Creates a new TerminalColors instance. */
    constructor($$source: Partial<TerminalColors> = {}) {
        if (!("black" in $$source)) {
            this["black"] = "";
        }
        if (!("red" in $$source)) {
            this["red"] = "";
        }
        if (!("green" in $$source)) {
            this["green"] = "";
        }
        if (!("yellow" in $$source)) {
            this["yellow"] = "";
        }
        if (!("blue" in $$source)) {
            this["blue"] = "";
        }
        if (!("magenta" in $$source)) {
            this["magenta"] = "";
        }
        if (!("cyan" in $$source)) {
            this["cyan"] = "";
        }
        if (!("white" in $$source)) {
            this["white"] = "";
        }
        if (!("brightBlack" in $$source)) {
            this["brightBlack"] = "";
        }
        if (!("brightRed" in $$source)) {
            this["brightRed"] = "";
        }
        if (!("brightGreen" in $$source)) {
            this["brightGreen"] = "";
        }
        if (!("brightYellow" in $$source)) {
            this["brightYellow"] = "";
        }
        if (!("brightBlue" in $$source)) {
            this["brightBlue"] = "";
        }
        if (!("brightMagenta" in $$source)) {
            this["brightMagenta"] = "";
        }
        if (!("brightCyan" in $$source)) {
            this["brightCyan"] = "";
        }
        if (!("brightWhite" in $$source)) {
            this["brightWhite"] = "";
        }
        if (!("background" in $$source)) {
            this["background"] = "";
        }
        if (!("foreground" in $$source)) {
            this["foreground"] = "";
        }
        if (!("cursor" in $$source)) {
            this["cursor"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalColors instance from a string or object.
     */
    static createFrom($$source: any = {}): TerminalColors {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TerminalColors($$parsedSource as Partial<TerminalColors>);
    }
}

export class ThemeDefinition {
    "name": string;
    "author": string;
    "appearance": string;
    "style": ThemeStyle;

    /** Creates a new ThemeDefinition instance. */
    constructor($$source: Partial<ThemeDefinition> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("appearance" in $$source)) {
            this["appearance"] = "";
        }
        if (!("style" in $$source)) {
            this["style"] = (new ThemeStyle());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThemeDefinition instance from a string or object.
     */
    static createFrom($$source: any = {}): ThemeDefinition {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("style" in $$parsedSource) {
            $$parsedSource["style"] = $$createField3_0($$parsedSource["style"]);
        }
        return new ThemeDefinition($$parsedSource as Partial<ThemeDefinition>);
    }
}

export class ThemeMeta {
    "name": string;
    "author": string;
    "appearance": string;
    "bundled": boolean;

    /** Creates a new ThemeMeta instance. */
    constructor($$source: Partial<ThemeMeta> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("appearance" in $$source)) {
            this["appearance"] = "";
        }
        if (!("bundled" in $$source)) {
            this["bundled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThemeMeta instance from a string or object.
     */
    static createFrom($$source: any = {}): ThemeMeta {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ThemeMeta($$parsedSource as Partial<ThemeMeta>);
    }
}

export class ThemeStyle {
    "bg": string;
    "bgElevated": string;
    "bgSubtle": string;
    "surface": string;
    "text": string;
    "textMuted": string;
    "textFaint": string;
    "border": string;
    "borderSubtle": string;
    "accent": string;
    "accentSubtle": string;
    "danger": string;
    "warning": string;
    "success": string;
    "info": string;
    "synKeyword": string;
    "synString": string;
    "synNumber": string;
    "synFn": string;
    "synComment": string;
    "terminal": TerminalColors;

    /** Creates a new ThemeStyle instance. */
    constructor($$source: Partial<ThemeStyle> = {}) {
        if (!("bg" in $$source)) {
            this["bg"] = "";
        }
        if (!("bgElevated" in $$source)) {
            this["bgElevated"] = "";
        }
        if (!("bgSubtle" in $$source)) {
            this["bgSubtle"] = "";
        }
        if (!("surface" in $$source)) {
            this["surface"] = "";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("textMuted" in $$source)) {
            this["textMuted"] = "";
        }
        if (!("textFaint" in $$source)) {
            this["textFaint"] = "";
        }
        if (!("border" in $$source)) {
            this["border"] = "";
        }
        if (!("borderSubtle" in $$source)) {
            this["borderSubtle"] = "";
        }
        if (!("accent" in $$source)) {
            this["accent"] = "";
        }
        if (!("accentSubtle" in $$source)) {
            this["accentSubtle"] = "";
        }
        if (!("danger" in $$source)) {
            this["danger"] = "";
        }
        if (!("warning" in $$source)) {
            this["warning"] = "";
        }
        if (!("success" in $$source)) {
            this["success"] = "";
        }
        if (!("info" in $$source)) {
            this["info"] = "";
        }
        if (!("synKeyword" in $$source)) {
            this["synKeyword"] = "";
        }
        if (!("synString" in $$source)) {
            this["synString"] = "";
        }
        if (!("synNumber" in $$source)) {
            this["synNumber"] = "";
        }
        if (!("synFn" in $$source)) {
            this["synFn"] = "";
        }
        if (!("synComment" in $$source)) {
            this["synComment"] = "";
        }
        if (!("terminal" in $$source)) {
            this["terminal"] = (new TerminalColors());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThemeStyle instance from a string or object.
     */
    static createFrom($$source: any = {}): ThemeStyle {
        const $$createField20_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("terminal" in $$parsedSource) {
            $$parsedSource["terminal"] = $$createField20_0($$parsedSource["terminal"]);
        }
        return new ThemeStyle($$parsedSource as Partial<ThemeStyle>);
    }
}

// Private type creation functions
const $$createType0 = ThemeStyle.createFrom;
const $$createType1 = TerminalColors.createFrom;
