// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class TerminalColors {
    /**
     * Creates a new TerminalColors instance.
     * @param {Partial<TerminalColors>} [$$source = {}] - The source object to create the TerminalColors.
     */
    constructor($$source = {}) {
        if (!("black" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["black"] = "";
        }
        if (!("red" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["red"] = "";
        }
        if (!("green" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["green"] = "";
        }
        if (!("yellow" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["yellow"] = "";
        }
        if (!("blue" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["blue"] = "";
        }
        if (!("magenta" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["magenta"] = "";
        }
        if (!("cyan" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cyan"] = "";
        }
        if (!("white" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["white"] = "";
        }
        if (!("brightBlack" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["brightBlack"] = "";
        }
        if (!("brightRed" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["brightRed"] = "";
        }
        if (!("brightGreen" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["brightGreen"] = "";
        }
        if (!("brightYellow" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["brightYellow"] = "";
        }
        if (!("brightBlue" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["brightBlue"] = "";
        }
        if (!("brightMagenta" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["brightMagenta"] = "";
        }
        if (!("brightCyan" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["brightCyan"] = "";
        }
        if (!("brightWhite" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["brightWhite"] = "";
        }
        if (!("background" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["background"] = "";
        }
        if (!("foreground" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["foreground"] = "";
        }
        if (!("cursor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cursor"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalColors instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TerminalColors}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TerminalColors(/** @type {Partial<TerminalColors>} */($$parsedSource));
    }
}

export class ThemeDefinition {
    /**
     * Creates a new ThemeDefinition instance.
     * @param {Partial<ThemeDefinition>} [$$source = {}] - The source object to create the ThemeDefinition.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["author"] = "";
        }
        if (!("appearance" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["appearance"] = "";
        }
        if (!("style" in $$source)) {
            /**
             * @member
             * @type {ThemeStyle}
             */
            this["style"] = (new ThemeStyle());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThemeDefinition instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ThemeDefinition}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("style" in $$parsedSource) {
            $$parsedSource["style"] = $$createField3_0($$parsedSource["style"]);
        }
        return new ThemeDefinition(/** @type {Partial<ThemeDefinition>} */($$parsedSource));
    }
}

export class ThemeMeta {
    /**
     * Creates a new ThemeMeta instance.
     * @param {Partial<ThemeMeta>} [$$source = {}] - The source object to create the ThemeMeta.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["author"] = "";
        }
        if (!("appearance" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["appearance"] = "";
        }
        if (!("bundled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["bundled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThemeMeta instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ThemeMeta}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ThemeMeta(/** @type {Partial<ThemeMeta>} */($$parsedSource));
    }
}

export class ThemeStyle {
    /**
     * Creates a new ThemeStyle instance.
     * @param {Partial<ThemeStyle>} [$$source = {}] - The source object to create the ThemeStyle.
     */
    constructor($$source = {}) {
        if (!("bg" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["bg"] = "";
        }
        if (!("bgElevated" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["bgElevated"] = "";
        }
        if (!("bgSubtle" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["bgSubtle"] = "";
        }
        if (!("surface" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["surface"] = "";
        }
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }
        if (!("textMuted" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["textMuted"] = "";
        }
        if (!("textFaint" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["textFaint"] = "";
        }
        if (!("border" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["border"] = "";
        }
        if (!("borderSubtle" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["borderSubtle"] = "";
        }
        if (!("accent" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["accent"] = "";
        }
        if (!("accentSubtle" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["accentSubtle"] = "";
        }
        if (!("danger" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["danger"] = "";
        }
        if (!("warning" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["warning"] = "";
        }
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["success"] = "";
        }
        if (!("info" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["info"] = "";
        }
        if (!("synKeyword" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["synKeyword"] = "";
        }
        if (!("synString" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["synString"] = "";
        }
        if (!("synNumber" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["synNumber"] = "";
        }
        if (!("synFn" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["synFn"] = "";
        }
        if (!("synComment" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["synComment"] = "";
        }
        if (!("terminal" in $$source)) {
            /**
             * @member
             * @type {TerminalColors}
             */
            this["terminal"] = (new TerminalColors());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThemeStyle instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ThemeStyle}
     */
    static createFrom($$source = {}) {
        const $$createField20_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("terminal" in $$parsedSource) {
            $$parsedSource["terminal"] = $$createField20_0($$parsedSource["terminal"]);
        }
        return new ThemeStyle(/** @type {Partial<ThemeStyle>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ThemeStyle.createFrom;
const $$createType1 = TerminalColors.createFrom;
