// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Get(name: string): $CancellablePromise<$models.ThemeDefinition> {
    return $Call.ByID(1752544013, name).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ImportFile(path: string): $CancellablePromise<$models.ThemeMeta> {
    return $Call.ByID(1736125820, path).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Install(data: string): $CancellablePromise<$models.ThemeMeta> {
    return $Call.ByID(81733810, data).then(($result: any) => {
        return $$createType1($result);
    });
}

export function List(): $CancellablePromise<$models.ThemeMeta[]> {
    return $Call.ByID(3486444427).then(($result: any) => {
        return $$createType2($result);
    });
}

export function Remove(name: string): $CancellablePromise<void> {
    return $Call.ByID(748025711, name);
}

// Private type creation functions
const $$createType0 = $models.ThemeDefinition.createFrom;
const $$createType1 = $models.ThemeMeta.createFrom;
const $$createType2 = $Create.Array($$createType1);
