// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} name
 * @returns {$CancellablePromise<$models.ThemeDefinition>}
 */
export function Get(name) {
    return $Call.ByID(1752544013, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<$models.ThemeMeta>}
 */
export function ImportFile(path) {
    return $Call.ByID(1736125820, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} data
 * @returns {$CancellablePromise<$models.ThemeMeta>}
 */
export function Install(data) {
    return $Call.ByID(81733810, data).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.ThemeMeta[]>}
 */
export function List() {
    return $Call.ByID(3486444427).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function Remove(name) {
    return $Call.ByID(748025711, name);
}

// Private type creation functions
const $$createType0 = $models.ThemeDefinition.createFrom;
const $$createType1 = $models.ThemeMeta.createFrom;
const $$createType2 = $Create.Array($$createType1);
