// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AppInfo(): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(3452410317).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ApplyUpdate opens the latest release page in the user's browser. In-place
 * binary replacement is not attempted here: macOS .app bundles are signed +
 * notarized and swapping the executable in-place breaks the bundle signature.
 * Users should download the new installer.
 */
export function ApplyUpdate(): $CancellablePromise<string> {
    return $Call.ByID(2502865495);
}

export function CheckForUpdate(): $CancellablePromise<$models.UpdateInfo> {
    return $Call.ByID(265129916).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CurrentVersion(): $CancellablePromise<string> {
    return $Call.ByID(823731153);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $models.UpdateInfo.createFrom;
