// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Request {
    "query": string;

    /**
     * optional override; defaults to workspace root
     */
    "root": string;
    "regex": boolean;
    "caseSensitive": boolean;
    "wholeWord": boolean;
    "includes": string[];
    "excludes": string[];

    /**
     * 0 means default cap
     */
    "maxResults": number;

    /** Creates a new Request instance. */
    constructor($$source: Partial<Request> = {}) {
        if (!("query" in $$source)) {
            this["query"] = "";
        }
        if (!("root" in $$source)) {
            this["root"] = "";
        }
        if (!("regex" in $$source)) {
            this["regex"] = false;
        }
        if (!("caseSensitive" in $$source)) {
            this["caseSensitive"] = false;
        }
        if (!("wholeWord" in $$source)) {
            this["wholeWord"] = false;
        }
        if (!("includes" in $$source)) {
            this["includes"] = [];
        }
        if (!("excludes" in $$source)) {
            this["excludes"] = [];
        }
        if (!("maxResults" in $$source)) {
            this["maxResults"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Request instance from a string or object.
     */
    static createFrom($$source: any = {}): Request {
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("includes" in $$parsedSource) {
            $$parsedSource["includes"] = $$createField5_0($$parsedSource["includes"]);
        }
        if ("excludes" in $$parsedSource) {
            $$parsedSource["excludes"] = $$createField6_0($$parsedSource["excludes"]);
        }
        return new Request($$parsedSource as Partial<Request>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
