// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service holds in-flight request state. Only one search runs at a time —
 * starting a new one cancels the previous; this matches the UX where the
 * user types and we re-run on debounce.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cancel stops the current search if its id matches. Stale cancels are no-ops
 * so frontend race conditions don't accidentally kill a fresh search.
 */
export function Cancel(id: string): $CancellablePromise<void> {
    return $Call.ByID(2759060495, id);
}

/**
 * Search starts an asynchronous search. The returned id is used for cancel
 * and to tag streaming events so stale results can be ignored on the client.
 */
export function Search(req: $models.Request): $CancellablePromise<string> {
    return $Call.ByID(2480453229, req);
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(3337136818, app);
}
