// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

export class Recent {
    /**
     * Creates a new Recent instance.
     * @param {Partial<Recent>} [$$source = {}] - The source object to create the Recent.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("lastUsed" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["lastUsed"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Recent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Recent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Recent(/** @type {Partial<Recent>} */($$parsedSource));
    }
}
