// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

export class Recent {
    "path": string;
    "lastUsed": time$0.Time;

    /** Creates a new Recent instance. */
    constructor($$source: Partial<Recent> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("lastUsed" in $$source)) {
            this["lastUsed"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Recent instance from a string or object.
     */
    static createFrom($$source: any = {}): Recent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Recent($$parsedSource as Partial<Recent>);
    }
}
