// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class LaunchConfig {
    "id": string;
    "label": string;
    "adapter": string;
    "request": string;
    "mode": string;
    "program": string;
    "cwd": string;
    "envFile": string;
    "env": { [_ in string]?: string };
    "args": string[];
    "buildFlags": string[];
    "disabled"?: boolean;
    "disabledNote"?: string;
    "language"?: string;

    /** Creates a new LaunchConfig instance. */
    constructor($$source: Partial<LaunchConfig> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("adapter" in $$source)) {
            this["adapter"] = "";
        }
        if (!("request" in $$source)) {
            this["request"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("program" in $$source)) {
            this["program"] = "";
        }
        if (!("cwd" in $$source)) {
            this["cwd"] = "";
        }
        if (!("envFile" in $$source)) {
            this["envFile"] = "";
        }
        if (!("env" in $$source)) {
            this["env"] = {};
        }
        if (!("args" in $$source)) {
            this["args"] = [];
        }
        if (!("buildFlags" in $$source)) {
            this["buildFlags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LaunchConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): LaunchConfig {
        const $$createField8_0 = $$createType0;
        const $$createField9_0 = $$createType1;
        const $$createField10_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("env" in $$parsedSource) {
            $$parsedSource["env"] = $$createField8_0($$parsedSource["env"]);
        }
        if ("args" in $$parsedSource) {
            $$parsedSource["args"] = $$createField9_0($$parsedSource["args"]);
        }
        if ("buildFlags" in $$parsedSource) {
            $$parsedSource["buildFlags"] = $$createField10_0($$parsedSource["buildFlags"]);
        }
        return new LaunchConfig($$parsedSource as Partial<LaunchConfig>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($Create.Any);
