// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class LaunchConfig {
    /**
     * Creates a new LaunchConfig instance.
     * @param {Partial<LaunchConfig>} [$$source = {}] - The source object to create the LaunchConfig.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("adapter" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["adapter"] = "";
        }
        if (!("request" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["request"] = "";
        }
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (!("program" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["program"] = "";
        }
        if (!("cwd" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cwd"] = "";
        }
        if (!("envFile" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["envFile"] = "";
        }
        if (!("env" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["env"] = {};
        }
        if (!("args" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["args"] = [];
        }
        if (!("buildFlags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["buildFlags"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["disabled"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["disabledNote"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["language"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LaunchConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LaunchConfig}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType0;
        const $$createField9_0 = $$createType1;
        const $$createField10_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("env" in $$parsedSource) {
            $$parsedSource["env"] = $$createField8_0($$parsedSource["env"]);
        }
        if ("args" in $$parsedSource) {
            $$parsedSource["args"] = $$createField9_0($$parsedSource["args"]);
        }
        if ("buildFlags" in $$parsedSource) {
            $$parsedSource["buildFlags"] = $$createField10_0($$parsedSource["buildFlags"]);
        }
        return new LaunchConfig(/** @type {Partial<LaunchConfig>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($Create.Any);
