// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (!("theme" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("terminalTheme" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["terminalTheme"] = "";
        }
        if (!("vimMode" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["vimMode"] = false;
        }
        if (!("uiFontSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["uiFontSize"] = 0;
        }
        if (!("bufferFontSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bufferFontSize"] = 0;
        }
        if (!("termFontSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["termFontSize"] = 0;
        }
        if (!("lineHeight" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lineHeight"] = "";
        }
        if (!("dlvPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dlvPath"] = "";
        }
        if (!("leftPanels" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["leftPanels"] = [];
        }
        if (!("rightPanels" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["rightPanels"] = [];
        }
        if (!("defaultLeftTab" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defaultLeftTab"] = "";
        }
        if (!("defaultRightTab" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defaultRightTab"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType0;
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("leftPanels" in $$parsedSource) {
            $$parsedSource["leftPanels"] = $$createField8_0($$parsedSource["leftPanels"]);
        }
        if ("rightPanels" in $$parsedSource) {
            $$parsedSource["rightPanels"] = $$createField9_0($$parsedSource["rightPanels"]);
        }
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
