// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Settings {
    "theme": string;
    "terminalTheme": string;
    "vimMode": boolean;
    "vimMappings": VimMapping[];
    "uiFontSize": number;
    "bufferFontSize": number;
    "termFontSize": number;
    "lineHeight": string;
    "dlvPath": string;

    /**
     * RestoreLastProject controls the auto-open behavior on launch. When true,
     * the most-recently-active project is reopened. When false, the user lands
     * on the welcome page.
     */
    "restoreLastProject"?: boolean | null;
    "leftPanels": string[];
    "rightPanels": string[];
    "defaultLeftTab": string;
    "defaultRightTab": string;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("terminalTheme" in $$source)) {
            this["terminalTheme"] = "";
        }
        if (!("vimMode" in $$source)) {
            this["vimMode"] = false;
        }
        if (!("vimMappings" in $$source)) {
            this["vimMappings"] = [];
        }
        if (!("uiFontSize" in $$source)) {
            this["uiFontSize"] = 0;
        }
        if (!("bufferFontSize" in $$source)) {
            this["bufferFontSize"] = 0;
        }
        if (!("termFontSize" in $$source)) {
            this["termFontSize"] = 0;
        }
        if (!("lineHeight" in $$source)) {
            this["lineHeight"] = "";
        }
        if (!("dlvPath" in $$source)) {
            this["dlvPath"] = "";
        }
        if (!("leftPanels" in $$source)) {
            this["leftPanels"] = [];
        }
        if (!("rightPanels" in $$source)) {
            this["rightPanels"] = [];
        }
        if (!("defaultLeftTab" in $$source)) {
            this["defaultLeftTab"] = "";
        }
        if (!("defaultRightTab" in $$source)) {
            this["defaultRightTab"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        const $$createField3_0 = $$createType1;
        const $$createField10_0 = $$createType2;
        const $$createField11_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("vimMappings" in $$parsedSource) {
            $$parsedSource["vimMappings"] = $$createField3_0($$parsedSource["vimMappings"]);
        }
        if ("leftPanels" in $$parsedSource) {
            $$parsedSource["leftPanels"] = $$createField10_0($$parsedSource["leftPanels"]);
        }
        if ("rightPanels" in $$parsedSource) {
            $$parsedSource["rightPanels"] = $$createField11_0($$parsedSource["rightPanels"]);
        }
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

export class VimMapping {
    "lhs": string;
    "rhs": string;

    /**
     * "normal" | "visual" | "insert"
     */
    "mode": string;

    /** Creates a new VimMapping instance. */
    constructor($$source: Partial<VimMapping> = {}) {
        if (!("lhs" in $$source)) {
            this["lhs"] = "";
        }
        if (!("rhs" in $$source)) {
            this["rhs"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VimMapping instance from a string or object.
     */
    static createFrom($$source: any = {}): VimMapping {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VimMapping($$parsedSource as Partial<VimMapping>);
    }
}

// Private type creation functions
const $$createType0 = VimMapping.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
