// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Settings {
    "theme": string;
    "terminalTheme": string;
    "vimMode": boolean;
    "uiFontSize": number;
    "bufferFontSize": number;
    "termFontSize": number;
    "lineHeight": string;
    "dlvPath": string;
    "leftPanels": string[];
    "rightPanels": string[];
    "defaultLeftTab": string;
    "defaultRightTab": string;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("terminalTheme" in $$source)) {
            this["terminalTheme"] = "";
        }
        if (!("vimMode" in $$source)) {
            this["vimMode"] = false;
        }
        if (!("uiFontSize" in $$source)) {
            this["uiFontSize"] = 0;
        }
        if (!("bufferFontSize" in $$source)) {
            this["bufferFontSize"] = 0;
        }
        if (!("termFontSize" in $$source)) {
            this["termFontSize"] = 0;
        }
        if (!("lineHeight" in $$source)) {
            this["lineHeight"] = "";
        }
        if (!("dlvPath" in $$source)) {
            this["dlvPath"] = "";
        }
        if (!("leftPanels" in $$source)) {
            this["leftPanels"] = [];
        }
        if (!("rightPanels" in $$source)) {
            this["rightPanels"] = [];
        }
        if (!("defaultLeftTab" in $$source)) {
            this["defaultLeftTab"] = "";
        }
        if (!("defaultRightTab" in $$source)) {
            this["defaultRightTab"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        const $$createField8_0 = $$createType0;
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("leftPanels" in $$parsedSource) {
            $$parsedSource["leftPanels"] = $$createField8_0($$parsedSource["leftPanels"]);
        }
        if ("rightPanels" in $$parsedSource) {
            $$parsedSource["rightPanels"] = $$createField9_0($$parsedSource["rightPanels"]);
        }
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
