// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.Settings>}
 */
export function Get() {
    return $Call.ByID(3785337334).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Reset() {
    return $Call.ByID(224651517);
}

/**
 * @param {$models.Settings} next
 * @returns {$CancellablePromise<void>}
 */
export function Update(next) {
    return $Call.ByID(3175012467, next);
}

// Private type creation functions
const $$createType0 = $models.Settings.createFrom;
